# Site settings
title: "Computing @ Olin"
# email:
description: >
  Computing at Franklin W. Olin College of Engineering.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "" # the base hostname & protocol for your site
timezone: America/New_York
