baseurl = "https://olin-computing.github.io/website/"
languageCode = "en-us"
title = "Computing at Franklin W. Olin College of Engineering"
theme = "hugo-alabaster-theme"
metadataformat = "yaml"

[params]
  name = "Olin Computing"
  description = "Computing at Franklin W. Olin College of Engineering."

  custom_css = ["site.css"]

	github_user = "olin-computing"
	github_repo = "website"

[params.sidebar]
	github_button  = true
	show_relations = true
