baseurl = "https://olin-computing.github.io/website/"
languageCode = "en-us"
title = "Computing @ Olin College"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
    description = "Computing at Franklin W. Olin College of Engineering."
	copyright = "Released under the MIT license"

	# provider = "GitHub"
	# repo_url = "https://github.com/olin-computing/website"

	custom_css = ["site.css"]

	[params.palette]
    primary = "light-blue"
    accent  = "teal"

[social]
	github  = "olin-computing"
